
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/puppy_vote?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
