version: "3.9"

services:
  puppy-vote-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABSE: puppy_vote
      TZ: Asia/Seoul
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower_case_table_names=1
    ports:
      - "3306:3306"

  puppy-vote-redis:
    image: redis:latest
    container_name: puppy-vote
    ports:
      - "6379:6379"